using System;
using System.IO;
using MiniRazor;

namespace Chloroplast.Core.Rendering
{
    /// <summary>
    /// Manages Razor compilation artifacts for better error diagnostics.
    /// Stores generated C# code in .chloroplast/artifacts/razor/ for debugging.
    /// </summary>
    public class RazorArtifactManager
    {
        private readonly string _artifactsPath;

        public RazorArtifactManager(string docsRoot)
        {
            _artifactsPath = Path.Combine(docsRoot, ".chloroplast", "artifacts", "razor");
        }

        /// <summary>
        /// Clears the artifacts directory before a new build run.
        /// </summary>
        public void CleanArtifacts()
        {
            if (Directory.Exists(_artifactsPath))
            {
                try
                {
                    Directory.Delete(_artifactsPath, recursive: true);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Warning: Failed to clean Razor artifacts directory: {ex.Message}");
                }
            }
        }

        /// <summary>
        /// Ensures the artifacts directory exists and is ready for use.
        /// Also creates .gitignore and README.txt if needed.
        /// </summary>
        public void EnsureArtifactsDirectory()
        {
            if (!Directory.Exists(_artifactsPath))
            {
                Directory.CreateDirectory(_artifactsPath);
            }

            // Ensure .chloroplast/.gitignore exists to prevent artifacts from being committed
            // _artifactsPath is something like: /path/to/docs/.chloroplast/artifacts/razor
            // We need to get to: /path/to/docs/.chloroplast
            var chloroplastDir = Path.GetDirectoryName(Path.GetDirectoryName(_artifactsPath));
            var gitignorePath = Path.Combine(chloroplastDir, ".gitignore");
            
            if (!File.Exists(gitignorePath))
            {
                try
                {
                    Directory.CreateDirectory(chloroplastDir);
                    File.WriteAllText(gitignorePath, "*\n");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Warning: Failed to create .chloroplast/.gitignore: {ex.Message}");
                }
            }

            // Ensure README.txt exists to explain the directory
            var readmePath = Path.Combine(chloroplastDir, "README.txt");
            if (!File.Exists(readmePath))
            {
                try
                {
                    var readmeContent = @"This directory contains build artifacts generated by Chloroplast.

The contents are automatically generated during each build and are safe to delete.
These files are ignored by git and should not be committed to source control.

Subdirectories:
- artifacts/razor/ - Generated C# source code from Razor template compilation
                     Useful for debugging template compilation errors
";
                    File.WriteAllText(readmePath, readmeContent);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Warning: Failed to create .chloroplast/README.txt: {ex.Message}");
                }
            }
        }

        /// <summary>
        /// Compiles a Razor template and saves the generated C# code to an artifact file.
        /// Returns the compiled template and the path to the artifact file.
        /// </summary>
        public (TemplateDescriptor template, string artifactPath) CompileTemplateWithArtifact(
            string templatePath, 
            string templateContent)
        {
            EnsureArtifactsDirectory();

            // Generate a unique but meaningful artifact filename
            var templateRelativeName = Path.GetFileName(templatePath);
            var timestamp = DateTime.UtcNow.ToString("yyyyMMdd_HHmmss");
            var artifactFileName = $"{Path.GetFileNameWithoutExtension(templateRelativeName)}_{timestamp}.cs";
            var artifactPath = Path.Combine(_artifactsPath, artifactFileName);

            // First, transpile to get the generated C# code
            string generatedCode;
            try
            {
                generatedCode = Razor.Transpile(templateContent);
            }
            catch (Exception ex)
            {
                // If transpilation fails, we can't save the artifact, but we still want to throw
                throw new Exception($"Failed to transpile template '{templatePath}'. " +
                    $"Unable to generate artifact for debugging.", ex);
            }

            // Save the generated code to the artifact file
            try
            {
                File.WriteAllText(artifactPath, generatedCode);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Warning: Failed to save Razor artifact to {artifactPath}: {ex.Message}");
            }

            // Now compile the template
            TemplateDescriptor compiledTemplate;
            try
            {
                compiledTemplate = Razor.Compile(templateContent);
            }
            catch (Exception ex)
            {
                // Enhance the exception with artifact path information
                throw new Exception($"Failed to compile Razor template '{templatePath}'.\n" +
                    $"Generated C# source code saved to: {artifactPath}\n" +
                    $"Original error: {ex.Message}", ex);
            }

            return (compiledTemplate, artifactPath);
        }
    }
}
