---
# Site configuration file sample for chloroplast

# site basics
title: Chlorplast Docs Portal sample
email: hello@wildernesslabs.co
description: >-
  Chloroplast by Wildenress Labs docs.

# razor templates
templates_folder: Templates

# main site folder
areas:
  - source_folder: /Docs
    output_folder: /

# API doc sets 
api_dirs:
  - title: Meadow.Core API
    project_uri: ../../Meadow.Core.csproj
    overrides_folder: /Meadow.Core.API_Overrides
    output_folder: /API/Meadow.Core
  - title: Meadow.Foundation API
    project_uri: ../../Meadow.Foundation.csproj
    overrides_folder: /Meadow.Foundation.API_Overrides
    output_folder: /API/Meadow.Foundation