---
# Site configuration file sample for chloroplast

# site basics
title: Chloroplast Docs
email: hello@wildernesslabs.co
description: >-
  Chloroplast by Wilderness Labs docs.

# base URL for sitemap generation
baseUrl: https://docs.wildernesslabs.co

# sitemap configuration
sitemap:
  enabled: true
  maxUrlsPerSitemap: 50000

# razor templates
templates_folder: templates

# main site folder
areas:
  - source_folder: /source
    output_folder: /
