---
# Site configuration file sample for chloroplast with localization support

# site basics
title: Chloroplast Docs
email: hello@wildernesslabs.co
description: >-
  Chloroplast by Wilderness Labs docs.

# base URL for sitemap generation and GitHub Pages deployment
baseUrl: https://wildernesslabs.github.io/Chloroplast/
basePath: /Chloroplast

# localization configuration
defaultLocale: en
supportedLocales:
  - en
  - es

# cache busting configuration
cacheBusting:
  enabled: true

# razor templates
templates_folder: templates

# main site folder
areas:
  - source_folder: /source
    output_folder: /
