name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.version.outputs.package_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Calculate version
      id: version
      run: |
        # Extract major.minor version from the Tool csproj file
        BASE_VERSION=$(grep '<Version.*>' toolsrc/Chloroplast.Tool/Chloroplast.Tool.csproj | sed 's/.*<Version[^>]*>\([^<]*\)<\/Version>.*/\1/' | sed 's/-dev//' | cut -d. -f1,2)
        VERSION="$BASE_VERSION.${{ github.run_number }}"
        echo "package_version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION (base: $BASE_VERSION)"
    - name: Install dependencies
      run: dotnet restore toolsrc
    - name: Build
      run: dotnet build --configuration Release --no-restore toolsrc
    - name: Test
      run: dotnet test --no-restore --verbosity normal toolsrc
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          toolsrc/Chloroplast.Core/bin/Release
          toolsrc/Chloroplast.Tool/bin/Release

  pack:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .
      - name: Pack Core
        run: dotnet pack toolsrc/Chloroplast.Core/ -p:Version=${{ needs.build.outputs.package_version }} --no-build
      - name: Pack Tool
        run: dotnet pack toolsrc/Chloroplast.Tool/ -p:Version=${{ needs.build.outputs.package_version }} --no-build
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            toolsrc/Chloroplast.Core/nupkg/*.nupkg
            toolsrc/Chloroplast.Tool/nupkg/*.nupkg

  publish:
    needs: pack
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: packages
      - name: List packages
        run: |
          echo "Packages directory contents:"
          ls -R packages
      - name: Add private GitHub registry to NuGet
        run: dotnet nuget add source https://nuget.pkg.github.com/WildernessLabs/index.json --name "github" --username WildernessLabs --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      - name: Push Core package to GitHub registry
        run: dotnet nuget push packages/Chloroplast.Core.*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      - name: Push Tool package to GitHub registry
        run: dotnet nuget push packages/Chloroplast.Tool.*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      - name: Push Tool package to nuget.org registry
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push packages/Chloroplast.Tool.*.nupkg --source "nuget.org" --api-key $NUGET_API_KEY --skip-duplicate

